#este es el dockerfile que usare en local, 
# asi no ejecuto migraciones ya que en local ya tengo el sync true (puede petar si la tabla migrations no está en local)
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3001
CMD ["node", "dist/main.js"] 